backend:
  name: git-gateway
  branch: master   # or "main" depending on your repo

media_folder: "images/uploads"    
public_folder: "/images/uploads"  

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      # Auto-apply the post.njk layout, hidden from editor
      - { label: "Layout", name: "layout", widget: "hidden", default: "post.njk" }
